[2025-03-05T16:19:28.087+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T16:19:28.098+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_setup_dag.setup_env_variables manual__2025-03-05T16:19:26.508281+00:00 [queued]>
[2025-03-05T16:19:28.106+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_setup_dag.setup_env_variables manual__2025-03-05T16:19:26.508281+00:00 [queued]>
[2025-03-05T16:19:28.106+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-05T16:19:28.115+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): setup_env_variables> on 2025-03-05 16:19:26.508281+00:00
[2025-03-05T16:19:28.122+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1098) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-05T16:19:28.123+0000] {standard_task_runner.py:72} INFO - Started process 1100 to run task
[2025-03-05T16:19:28.124+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_setup_dag', 'setup_env_variables', 'manual__2025-03-05T16:19:26.508281+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/etl_setup_dag.py', '--cfg-path', '/tmp/tmptk9iaxaq']
[2025-03-05T16:19:28.126+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask setup_env_variables
[2025-03-05T16:19:28.175+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_setup_dag.setup_env_variables manual__2025-03-05T16:19:26.508281+00:00 [running]> on host bb5f6a2f96ec
[2025-03-05T16:19:28.256+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_setup_dag' AIRFLOW_CTX_TASK_ID='setup_env_variables' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T16:19:26.508281+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-05T16:19:26.508281+00:00'
[2025-03-05T16:19:28.257+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-05T16:19:28.269+0000] {logging_mixin.py:190} INFO - Successfully loaded API_KEY
[2025-03-05T16:19:28.269+0000] {logging_mixin.py:190} INFO - Error loading cities: name 'ENV_PATH' is not defined
[2025-03-05T16:19:28.270+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_setup_dag.py", line 20, in setup_process
    cities = load_env_cities()
             ^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/encodings_setup.py", line 34, in load_env_cities
    load_dotenv(ENV_PATH)
                ^^^^^^^^
NameError: name 'ENV_PATH' is not defined
[2025-03-05T16:19:28.282+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=etl_setup_dag, task_id=setup_env_variables, run_id=manual__2025-03-05T16:19:26.508281+00:00, execution_date=20250305T161926, start_date=20250305T161928, end_date=20250305T161928
[2025-03-05T16:19:28.300+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-05T16:19:28.300+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 12 for task setup_env_variables (name 'ENV_PATH' is not defined; 1100)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_setup_dag.py", line 20, in setup_process
    cities = load_env_cities()
             ^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/encodings_setup.py", line 34, in load_env_cities
    load_dotenv(ENV_PATH)
                ^^^^^^^^
NameError: name 'ENV_PATH' is not defined
[2025-03-05T16:19:28.337+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-05T16:19:28.349+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-05T16:19:28.350+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
