[2025-03-05T15:01:39.440+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T15:01:39.460+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_postgres_connection.test_postgres_connection_task manual__2025-03-05T15:01:37.906926+00:00 [queued]>
[2025-03-05T15:01:39.469+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_postgres_connection.test_postgres_connection_task manual__2025-03-05T15:01:37.906926+00:00 [queued]>
[2025-03-05T15:01:39.469+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-05T15:01:39.483+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): test_postgres_connection_task> on 2025-03-05 15:01:37.906926+00:00
[2025-03-05T15:01:39.489+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=105) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-05T15:01:39.490+0000] {standard_task_runner.py:72} INFO - Started process 106 to run task
[2025-03-05T15:01:39.492+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_postgres_connection', 'test_postgres_connection_task', 'manual__2025-03-05T15:01:37.906926+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/db_connection_test_dag.py', '--cfg-path', '/tmp/tmpnqc9e376']
[2025-03-05T15:01:39.494+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask test_postgres_connection_task
[2025-03-05T15:01:39.532+0000] {task_command.py:467} INFO - Running <TaskInstance: test_postgres_connection.test_postgres_connection_task manual__2025-03-05T15:01:37.906926+00:00 [running]> on host bb5f6a2f96ec
[2025-03-05T15:01:39.588+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_postgres_connection' AIRFLOW_CTX_TASK_ID='test_postgres_connection_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T15:01:37.906926+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-05T15:01:37.906926+00:00'
[2025-03-05T15:01:39.591+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-05T15:01:39.608+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-05T15:01:39.667+0000] {logging_mixin.py:190} INFO - Connection successful! Query result: (1,)
[2025-03-05T15:01:39.667+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-05T15:01:39.676+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-05T15:01:39.676+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=test_postgres_connection, task_id=test_postgres_connection_task, run_id=manual__2025-03-05T15:01:37.906926+00:00, execution_date=20250305T150137, start_date=20250305T150139, end_date=20250305T150139
[2025-03-05T15:01:39.707+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T15:01:39.722+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-05T15:01:39.723+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
