[2025-03-01T15:56:29.025+0000] {processor.py:186} INFO - Started process (PID=211) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:56:29.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T15:56:29.027+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:56:29.027+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:56:29.050+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:56:29.249+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:56:29.249+0000] {override.py:1912} INFO - Created Permission View: can read on DAG:test_postgres_connection
[2025-03-01T15:56:29.256+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:56:29.256+0000] {override.py:1912} INFO - Created Permission View: can edit on DAG:test_postgres_connection
[2025-03-01T15:56:29.261+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:56:29.260+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG:test_postgres_connection
[2025-03-01T15:56:29.265+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:56:29.265+0000] {override.py:1912} INFO - Created Permission View: can read on DAG Run:test_postgres_connection
[2025-03-01T15:56:29.269+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:56:29.269+0000] {override.py:1912} INFO - Created Permission View: can create on DAG Run:test_postgres_connection
[2025-03-01T15:56:29.274+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:56:29.273+0000] {override.py:1912} INFO - Created Permission View: menu access on DAG Run:test_postgres_connection
[2025-03-01T15:56:29.278+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:56:29.278+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG Run:test_postgres_connection
[2025-03-01T15:56:29.278+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:56:29.278+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T15:56:29.408+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:56:29.408+0000] {dag.py:3262} INFO - Creating ORM DAG for test_postgres_connection
[2025-03-01T15:56:29.409+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:56:29.409+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T15:56:29.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.403 seconds
[2025-03-01T15:57:00.178+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:57:00.178+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T15:57:00.180+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:57:00.180+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:57:00.188+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:57:00.214+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:57:00.213+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T15:57:00.233+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:57:00.232+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T15:57:00.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.077 seconds
[2025-03-01T15:57:30.431+0000] {processor.py:186} INFO - Started process (PID=229) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:57:30.432+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T15:57:30.435+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:57:30.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:57:30.445+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:57:30.472+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:57:30.472+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T15:57:30.489+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:57:30.489+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T15:57:30.507+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.091 seconds
[2025-03-01T15:58:00.683+0000] {processor.py:186} INFO - Started process (PID=238) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:58:00.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T15:58:00.686+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:58:00.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:58:00.694+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:58:00.712+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:58:00.712+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T15:58:00.723+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:58:00.723+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T15:58:00.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.057 seconds
[2025-03-01T15:58:30.894+0000] {processor.py:186} INFO - Started process (PID=246) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:58:30.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T15:58:30.897+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:58:30.896+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:58:30.904+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:58:30.924+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:58:30.924+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T15:58:30.935+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:58:30.935+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T15:58:30.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.059 seconds
[2025-03-01T15:59:01.136+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:59:01.137+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T15:59:01.139+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:59:01.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:59:01.150+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:59:01.171+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:59:01.170+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T15:59:01.182+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:59:01.182+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T15:59:01.195+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.074 seconds
[2025-03-01T15:59:31.344+0000] {processor.py:186} INFO - Started process (PID=263) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:59:31.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T15:59:31.347+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:59:31.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:59:31.354+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T15:59:31.373+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:59:31.373+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T15:59:31.384+0000] {logging_mixin.py:190} INFO - [2025-03-01T15:59:31.384+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T15:59:31.397+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.057 seconds
[2025-03-01T16:00:01.544+0000] {processor.py:186} INFO - Started process (PID=271) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:00:01.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:00:01.547+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:00:01.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:00:01.554+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:00:01.572+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:00:01.572+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:00:01.583+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:00:01.583+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:00:01.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.057 seconds
[2025-03-01T16:00:31.752+0000] {processor.py:186} INFO - Started process (PID=280) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:00:31.752+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:00:31.754+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:00:31.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:00:31.762+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:00:31.781+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:00:31.781+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:00:31.800+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:00:31.800+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:00:31.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.071 seconds
[2025-03-01T16:01:01.972+0000] {processor.py:186} INFO - Started process (PID=288) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:01:01.972+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:01:01.974+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:01:01.974+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:01:01.982+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:01:02.000+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:01:02.000+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:01:02.018+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:01:02.018+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:01:02.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.063 seconds
[2025-03-01T16:01:32.182+0000] {processor.py:186} INFO - Started process (PID=295) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:01:32.182+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:01:32.184+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:01:32.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:01:32.191+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:01:32.210+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:01:32.210+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:01:32.221+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:01:32.221+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:01:32.235+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.058 seconds
[2025-03-01T16:02:01.377+0000] {processor.py:186} INFO - Started process (PID=305) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:02:01.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:02:01.379+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:02:01.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:02:01.408+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:02:01.396+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:02:01.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:02:01.417+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.045 seconds
[2025-03-01T16:02:02.404+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:02:02.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:02:02.407+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:02:02.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:02:02.423+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:02:02.422+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:02:02.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:02:02.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.032 seconds
[2025-03-01T16:02:32.576+0000] {processor.py:186} INFO - Started process (PID=315) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:02:32.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:02:32.579+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:02:32.579+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:02:32.596+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:02:32.594+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:02:32.596+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:02:32.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.032 seconds
[2025-03-01T16:03:02.773+0000] {processor.py:186} INFO - Started process (PID=323) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:03:02.774+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:03:02.776+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:03:02.775+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:03:02.804+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:03:02.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:03:02.805+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:03:02.814+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.047 seconds
[2025-03-01T16:03:32.975+0000] {processor.py:186} INFO - Started process (PID=331) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:03:32.976+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:03:32.977+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:03:32.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:03:32.993+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:03:32.992+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:03:32.995+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:03:33.079+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:03:33.079+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:03:33.089+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:03:33.089+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:03:33.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.133 seconds
[2025-03-01T16:04:03.255+0000] {processor.py:186} INFO - Started process (PID=339) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:04:03.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:04:03.257+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:04:03.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:04:03.273+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:04:03.273+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:04:03.276+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:04:03.288+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:04:03.288+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:04:03.299+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:04:03.299+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:04:03.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.062 seconds
[2025-03-01T16:04:24.418+0000] {processor.py:186} INFO - Started process (PID=346) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:04:24.419+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:04:24.420+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:04:24.420+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:04:24.437+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:04:24.437+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:04:24.441+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:04:24.454+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:04:24.454+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:04:24.465+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:04:24.465+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:04:24.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.065 seconds
[2025-03-01T16:04:54.629+0000] {processor.py:186} INFO - Started process (PID=354) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:04:54.630+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:04:54.631+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:04:54.631+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:04:54.647+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:04:54.646+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:04:54.649+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:04:54.661+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:04:54.661+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:04:54.672+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:04:54.672+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:04:54.684+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.060 seconds
[2025-03-01T16:05:24.833+0000] {processor.py:186} INFO - Started process (PID=362) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:05:24.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:05:24.834+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:05:24.834+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:05:24.851+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:05:24.851+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:05:24.855+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:05:24.869+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:05:24.868+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:05:24.882+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:05:24.882+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:05:24.905+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.076 seconds
[2025-03-01T16:05:55.057+0000] {processor.py:186} INFO - Started process (PID=370) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:05:55.058+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:05:55.059+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:05:55.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:05:55.074+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:05:55.074+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:05:55.077+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:05:55.095+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:05:55.095+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:05:55.106+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:05:55.106+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:05:55.118+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.065 seconds
[2025-03-01T16:06:25.263+0000] {processor.py:186} INFO - Started process (PID=378) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:06:25.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:06:25.265+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:06:25.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:06:25.280+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:06:25.280+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:06:25.283+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:06:25.297+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:06:25.297+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:06:25.308+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:06:25.308+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:06:25.323+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.064 seconds
[2025-03-01T16:06:55.497+0000] {processor.py:186} INFO - Started process (PID=386) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:06:55.498+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:06:55.499+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:06:55.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:06:55.514+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:06:55.514+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:06:55.517+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:06:55.529+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:06:55.529+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:06:55.543+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:06:55.542+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:06:55.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.063 seconds
[2025-03-01T16:07:25.695+0000] {processor.py:186} INFO - Started process (PID=393) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:07:25.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:07:25.697+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:07:25.697+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:07:25.713+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:07:25.713+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:07:25.715+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:07:25.727+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:07:25.727+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:07:25.739+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:07:25.739+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:07:25.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.061 seconds
[2025-03-01T16:07:55.907+0000] {processor.py:186} INFO - Started process (PID=401) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:07:55.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:07:55.910+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:07:55.909+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:07:55.930+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:07:55.930+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:07:55.934+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:07:55.952+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:07:55.952+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:07:55.969+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:07:55.969+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:07:55.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.089 seconds
[2025-03-01T16:08:26.042+0000] {processor.py:186} INFO - Started process (PID=410) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:08:26.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:08:26.043+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:08:26.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:08:26.060+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:08:26.060+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:08:26.062+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:08:26.074+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:08:26.074+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:08:26.086+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:08:26.086+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:08:26.100+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.063 seconds
[2025-03-01T16:08:56.249+0000] {processor.py:186} INFO - Started process (PID=418) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:08:56.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:08:56.252+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:08:56.251+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:08:56.283+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:08:56.283+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:08:56.290+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:08:56.306+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:08:56.306+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:08:56.318+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:08:56.318+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:08:56.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.087 seconds
[2025-03-01T16:09:26.490+0000] {processor.py:186} INFO - Started process (PID=426) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:09:26.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:09:26.493+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:09:26.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:09:26.513+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:09:26.513+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:09:26.517+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:09:26.536+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:09:26.535+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:09:26.551+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:09:26.551+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:09:26.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.087 seconds
[2025-03-01T16:09:56.630+0000] {processor.py:186} INFO - Started process (PID=434) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:09:56.631+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:09:56.632+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:09:56.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:09:56.650+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:09:56.650+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:09:56.654+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:09:56.673+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:09:56.672+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:09:56.690+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:09:56.690+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:09:56.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.082 seconds
[2025-03-01T16:10:26.863+0000] {processor.py:186} INFO - Started process (PID=442) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:10:26.864+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:10:26.864+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:10:26.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:10:26.880+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:10:26.880+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:10:26.883+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:10:26.895+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:10:26.895+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:10:26.906+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:10:26.906+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:10:26.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.063 seconds
[2025-03-01T16:10:57.069+0000] {processor.py:186} INFO - Started process (PID=451) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:10:57.070+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:10:57.071+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:10:57.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:10:57.088+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:10:57.088+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:10:57.091+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:10:57.104+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:10:57.104+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:10:57.115+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:10:57.115+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:10:57.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.065 seconds
[2025-03-01T16:11:27.282+0000] {processor.py:186} INFO - Started process (PID=459) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:11:27.283+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:11:27.284+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:11:27.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:11:27.300+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:11:27.300+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:11:27.302+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:11:27.315+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:11:27.314+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:11:27.326+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:11:27.325+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:11:27.338+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.061 seconds
[2025-03-01T16:11:57.482+0000] {processor.py:186} INFO - Started process (PID=467) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:11:57.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:11:57.484+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:11:57.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:11:57.508+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:11:57.507+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:11:57.510+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:11:57.522+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:11:57.522+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:11:57.533+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:11:57.533+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:11:57.546+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.071 seconds
[2025-03-01T16:12:27.697+0000] {processor.py:186} INFO - Started process (PID=475) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:12:27.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:12:27.698+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:12:27.698+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:12:27.715+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:12:27.715+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:12:27.717+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:12:27.731+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:12:27.731+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:12:27.743+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:12:27.742+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:12:27.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.065 seconds
[2025-03-01T16:12:57.901+0000] {processor.py:186} INFO - Started process (PID=483) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:12:57.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:12:57.904+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:12:57.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:12:57.926+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:12:57.926+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:12:57.930+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:12:57.949+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:12:57.949+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:12:57.967+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:12:57.966+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:12:58.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.112 seconds
[2025-03-01T16:13:28.162+0000] {processor.py:186} INFO - Started process (PID=492) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:13:28.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:13:28.165+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:13:28.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:13:28.186+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:13:28.186+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:13:28.188+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:13:28.201+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:13:28.201+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:13:28.212+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:13:28.212+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:13:28.225+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.070 seconds
[2025-03-01T16:13:58.376+0000] {processor.py:186} INFO - Started process (PID=501) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:13:58.377+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:13:58.379+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:13:58.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:13:58.400+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:13:58.400+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:13:58.404+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:13:58.422+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:13:58.421+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:13:58.439+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:13:58.439+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:13:58.458+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.089 seconds
[2025-03-01T16:14:28.625+0000] {processor.py:186} INFO - Started process (PID=509) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:14:28.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:14:28.627+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:14:28.627+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:14:28.642+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:14:28.642+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:14:28.644+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:14:28.657+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:14:28.657+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:14:28.668+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:14:28.667+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:14:28.680+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.059 seconds
[2025-03-01T16:14:58.835+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:14:58.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:14:58.837+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:14:58.836+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:14:58.852+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:14:58.852+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:14:58.855+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:14:58.868+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:14:58.868+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:14:58.879+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:14:58.879+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:14:58.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.061 seconds
[2025-03-01T16:15:29.028+0000] {processor.py:186} INFO - Started process (PID=525) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:15:29.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:15:29.029+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:15:29.029+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:15:29.045+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:15:29.045+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:15:29.048+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:15:29.062+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:15:29.062+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:15:29.081+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:15:29.080+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:15:29.093+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.070 seconds
[2025-03-01T16:15:59.239+0000] {processor.py:186} INFO - Started process (PID=533) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:15:59.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:15:59.241+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:15:59.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:15:59.257+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:15:59.257+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:15:59.260+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:15:59.272+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:15:59.272+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:15:59.283+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:15:59.283+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:15:59.296+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.061 seconds
[2025-03-01T16:16:29.465+0000] {processor.py:186} INFO - Started process (PID=541) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:16:29.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:16:29.467+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:16:29.467+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:16:29.488+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:16:29.488+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:16:29.492+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:16:29.519+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:16:29.519+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:16:29.557+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:16:29.557+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:16:29.610+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.153 seconds
[2025-03-01T16:16:59.790+0000] {processor.py:186} INFO - Started process (PID=549) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:16:59.791+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:16:59.792+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:16:59.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:16:59.815+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:16:59.815+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:16:59.818+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:16:59.837+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:16:59.837+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:16:59.854+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:16:59.854+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:16:59.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.089 seconds
[2025-03-01T16:17:29.935+0000] {processor.py:186} INFO - Started process (PID=557) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:17:29.936+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:17:29.937+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:17:29.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:17:29.953+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:17:29.952+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:17:29.955+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:17:29.968+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:17:29.968+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:17:29.979+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:17:29.979+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:17:29.993+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.062 seconds
[2025-03-01T16:18:00.129+0000] {processor.py:186} INFO - Started process (PID=565) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:18:00.130+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:18:00.131+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:18:00.131+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:18:00.149+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:18:00.149+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:18:00.152+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:18:00.165+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:18:00.165+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:18:00.177+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:18:00.177+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:18:00.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.066 seconds
[2025-03-01T16:18:30.360+0000] {processor.py:186} INFO - Started process (PID=573) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:18:30.361+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:18:30.362+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:18:30.361+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:18:30.376+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:18:30.376+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:18:30.379+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:18:30.391+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:18:30.391+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:18:30.405+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:18:30.405+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:18:30.417+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.063 seconds
[2025-03-01T16:19:00.556+0000] {processor.py:186} INFO - Started process (PID=581) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:19:00.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:19:00.557+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:19:00.557+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:19:00.572+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:19:00.572+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:19:00.575+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:19:00.588+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:19:00.588+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:19:00.599+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:19:00.598+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:19:00.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.061 seconds
[2025-03-01T16:19:30.754+0000] {processor.py:186} INFO - Started process (PID=589) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:19:30.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:19:30.756+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:19:30.756+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:19:30.771+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:19:30.771+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:19:30.774+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:19:30.786+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:19:30.786+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:19:30.797+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:19:30.797+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:19:30.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.060 seconds
[2025-03-01T16:20:00.952+0000] {processor.py:186} INFO - Started process (PID=597) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:20:00.953+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:20:00.954+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:20:00.953+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:20:00.970+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:20:00.970+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:20:00.972+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:20:00.986+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:20:00.986+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:20:00.998+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:20:00.998+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:20:01.010+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.063 seconds
[2025-03-01T16:20:31.145+0000] {processor.py:186} INFO - Started process (PID=606) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:20:31.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:20:31.147+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:20:31.146+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:20:31.163+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:20:31.163+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:20:31.165+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:20:31.177+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:20:31.177+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:20:31.190+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:20:31.189+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:20:31.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.064 seconds
[2025-03-01T16:21:01.354+0000] {processor.py:186} INFO - Started process (PID=615) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:21:01.355+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:21:01.356+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:21:01.356+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:21:01.378+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:21:01.378+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:21:01.382+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:21:01.405+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:21:01.404+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:21:01.422+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:21:01.422+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:21:01.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.094 seconds
[2025-03-01T16:21:31.596+0000] {processor.py:186} INFO - Started process (PID=624) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:21:31.597+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:21:31.597+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:21:31.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:21:31.612+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:21:31.612+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:21:31.615+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:21:31.628+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:21:31.628+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:21:31.639+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:21:31.639+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:21:31.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.060 seconds
[2025-03-01T16:22:01.790+0000] {processor.py:186} INFO - Started process (PID=633) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:22:01.791+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:22:01.792+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:22:01.791+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:22:01.807+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:22:01.807+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:22:01.809+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:22:01.821+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:22:01.821+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:22:01.832+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:22:01.832+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:22:01.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.060 seconds
[2025-03-01T16:22:31.984+0000] {processor.py:186} INFO - Started process (PID=643) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:22:31.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:22:31.985+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:22:31.985+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:22:32.000+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:22:32.000+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:22:32.003+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:22:32.015+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:22:32.015+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:22:32.025+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:22:32.025+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:22:32.038+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.060 seconds
[2025-03-01T16:23:02.181+0000] {processor.py:186} INFO - Started process (PID=651) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:23:02.181+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:23:02.182+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:23:02.182+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:23:02.198+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:23:02.197+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:23:02.200+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:23:02.212+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:23:02.212+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:23:02.223+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:23:02.223+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:23:02.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.061 seconds
[2025-03-01T16:23:32.398+0000] {processor.py:186} INFO - Started process (PID=659) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:23:32.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:23:32.400+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:23:32.400+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:23:32.416+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:23:32.416+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T16:23:32.421+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:23:32.440+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:23:32.439+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T16:23:32.460+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:23:32.460+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T16:23:32.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.084 seconds
[2025-03-01T16:26:27.892+0000] {processor.py:186} INFO - Started process (PID=66) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:26:27.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:26:27.918+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:26:27.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:26:28.048+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:26:28.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:26:28.054+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:26:28.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.210 seconds
[2025-03-01T16:26:58.229+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:26:58.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:26:58.242+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:26:58.241+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:26:58.272+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:26:58.267+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:26:58.273+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:26:58.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.073 seconds
[2025-03-01T16:27:28.477+0000] {processor.py:186} INFO - Started process (PID=81) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:27:28.477+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:27:28.480+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:27:28.479+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:27:28.506+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:27:28.504+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:27:28.506+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:27:28.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.055 seconds
[2025-03-01T16:27:58.706+0000] {processor.py:186} INFO - Started process (PID=90) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:27:58.706+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:27:58.708+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:27:58.708+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:27:58.724+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:27:58.723+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:27:58.725+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:27:58.732+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.030 seconds
[2025-03-01T16:28:28.888+0000] {processor.py:186} INFO - Started process (PID=98) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:28:28.888+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:28:28.890+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:28:28.890+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:28:28.908+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:28:28.907+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:28:28.908+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:28:28.916+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.032 seconds
[2025-03-01T16:28:59.063+0000] {processor.py:186} INFO - Started process (PID=106) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:28:59.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:28:59.065+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:28:59.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:28:59.082+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:28:59.080+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:28:59.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:28:59.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.031 seconds
[2025-03-01T16:29:29.262+0000] {processor.py:186} INFO - Started process (PID=114) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:29:29.262+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:29:29.264+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:29:29.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:29:29.282+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:29:29.280+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:29:29.283+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:29:29.293+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.036 seconds
[2025-03-01T16:29:59.462+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:29:59.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:29:59.464+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:29:59.464+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:29:59.480+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:29:59.479+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:29:59.481+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:29:59.488+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.032 seconds
[2025-03-01T16:30:29.639+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:30:29.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:30:29.641+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:30:29.641+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:30:29.658+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:30:29.657+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:30:29.658+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:30:29.665+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.031 seconds
[2025-03-01T16:30:59.983+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:30:59.998+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:31:00.006+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:31:00.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:31:00.069+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:31:00.066+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:31:00.072+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:31:00.096+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.232 seconds
[2025-03-01T16:33:51.387+0000] {processor.py:186} INFO - Started process (PID=67) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:33:51.398+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:33:51.400+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:33:51.399+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:33:51.577+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:33:51.575+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:33:51.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:33:51.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.297 seconds
[2025-03-01T16:34:21.928+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:34:21.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:34:21.938+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:34:21.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:34:21.966+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:34:21.962+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:34:21.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:34:21.974+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.052 seconds
[2025-03-01T16:34:52.118+0000] {processor.py:186} INFO - Started process (PID=83) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:34:52.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:34:52.121+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:34:52.120+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:34:52.141+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:34:52.138+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:34:52.141+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:34:52.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.034 seconds
[2025-03-01T16:35:22.296+0000] {processor.py:186} INFO - Started process (PID=91) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:35:22.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:35:22.299+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:35:22.299+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:35:22.319+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:35:22.316+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:35:22.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:35:22.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.034 seconds
[2025-03-01T16:35:52.479+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:35:52.479+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:35:52.481+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:35:52.481+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:35:52.501+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:35:52.498+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:35:52.502+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:35:52.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.035 seconds
[2025-03-01T16:36:22.676+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:36:22.677+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:36:22.678+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:36:22.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:36:22.698+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:36:22.695+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:36:22.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:36:22.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.037 seconds
[2025-03-01T16:36:52.856+0000] {processor.py:186} INFO - Started process (PID=116) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:36:52.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:36:52.858+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:36:52.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:36:52.874+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:36:52.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:36:52.875+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:36:52.886+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.034 seconds
[2025-03-01T16:37:23.040+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:37:23.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:37:23.044+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:37:23.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:37:23.072+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:37:23.068+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:37:23.073+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:37:23.092+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.058 seconds
[2025-03-01T16:37:53.249+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:37:53.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:37:53.251+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:37:53.251+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:37:53.267+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:37:53.266+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:37:53.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:37:53.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.030 seconds
[2025-03-01T16:38:23.437+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:38:23.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:38:23.448+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:38:23.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:38:23.489+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:38:23.487+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:38:23.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:38:23.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.091 seconds
[2025-03-01T16:38:53.606+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:38:53.607+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:38:53.609+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:38:53.609+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:38:53.635+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:38:53.629+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:38:53.636+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:38:53.647+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.048 seconds
[2025-03-01T16:39:23.846+0000] {processor.py:186} INFO - Started process (PID=157) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:39:23.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T16:39:23.848+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:39:23.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:39:23.864+0000] {logging_mixin.py:190} INFO - [2025-03-01T16:39:23.863+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T16:39:23.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T16:39:23.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.031 seconds
[2025-03-01T17:15:00.341+0000] {processor.py:186} INFO - Started process (PID=69) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:15:00.359+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:15:00.366+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:15:00.366+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:15:00.525+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:15:00.523+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T17:15:00.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:15:00.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.230 seconds
[2025-03-01T17:15:30.636+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:15:30.648+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:15:30.650+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:15:30.650+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:15:30.675+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:15:30.671+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T17:15:30.676+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:15:30.683+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.053 seconds
[2025-03-01T17:16:00.869+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:16:00.870+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:16:00.871+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:16:00.871+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:16:00.896+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:16:00.892+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T17:16:00.896+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:16:00.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.039 seconds
[2025-03-01T17:20:41.475+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:20:41.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:20:41.493+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:20:41.493+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:20:41.664+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:20:41.663+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T17:20:41.665+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:20:41.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.264 seconds
[2025-03-01T17:21:11.800+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:21:11.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:21:11.808+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:21:11.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:21:11.834+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:21:11.829+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T17:21:11.835+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:21:11.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.052 seconds
[2025-03-01T17:21:41.996+0000] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:21:41.996+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:21:41.998+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:21:41.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:21:42.019+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:21:42.015+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T17:21:42.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:21:42.027+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.036 seconds
[2025-03-01T17:22:12.183+0000] {processor.py:186} INFO - Started process (PID=89) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:22:12.184+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:22:12.186+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:22:12.186+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:22:12.203+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:22:12.201+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T17:22:12.203+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:22:12.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.032 seconds
[2025-03-01T17:22:42.362+0000] {processor.py:186} INFO - Started process (PID=97) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:22:42.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:22:42.364+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:22:42.364+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:22:42.381+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:22:42.380+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T17:22:42.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:22:42.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.032 seconds
[2025-03-01T17:23:12.576+0000] {processor.py:186} INFO - Started process (PID=106) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:23:12.576+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:23:12.578+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:23:12.578+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:23:12.595+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:23:12.594+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T17:23:12.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:23:12.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.031 seconds
[2025-03-01T17:23:42.764+0000] {processor.py:186} INFO - Started process (PID=114) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:23:42.765+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:23:42.767+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:23:42.767+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:23:42.789+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:23:42.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T17:23:42.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:23:42.810+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.053 seconds
[2025-03-01T17:24:12.984+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:24:12.985+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:24:12.987+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:24:12.987+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:24:13.011+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:24:13.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T17:24:13.011+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:24:13.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.054 seconds
[2025-03-01T17:24:43.237+0000] {processor.py:186} INFO - Started process (PID=130) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:24:43.237+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:24:43.239+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:24:43.239+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:24:43.255+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:24:43.254+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T17:24:43.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:24:43.264+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.032 seconds
[2025-03-01T17:25:13.412+0000] {processor.py:186} INFO - Started process (PID=138) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:25:13.413+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:25:13.415+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:25:13.414+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:25:13.432+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:25:13.431+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/db_connection_test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/db_connection_test_dag.py", line 65, in <module>
    add_postgres_connection()
  File "/opt/airflow/dags/db_connection_test_dag.py", line 48, in add_postgres_connection
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_weather_conn` isn't defined
[2025-03-01T17:25:13.432+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:25:13.440+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.032 seconds
[2025-03-01T17:28:52.135+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:28:52.139+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:28:52.142+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:28:52.142+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:28:52.278+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:28:52.278+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T17:28:52.287+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:28:53.219+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:28:53.218+0000] {override.py:1912} INFO - Created Permission View: can edit on DAG:test_postgres_connection
[2025-03-01T17:28:53.242+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:28:53.241+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG:test_postgres_connection
[2025-03-01T17:28:53.255+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:28:53.254+0000] {override.py:1912} INFO - Created Permission View: can read on DAG:test_postgres_connection
[2025-03-01T17:28:53.265+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:28:53.265+0000] {override.py:1912} INFO - Created Permission View: menu access on DAG Run:test_postgres_connection
[2025-03-01T17:28:53.277+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:28:53.277+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG Run:test_postgres_connection
[2025-03-01T17:28:53.289+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:28:53.289+0000] {override.py:1912} INFO - Created Permission View: can create on DAG Run:test_postgres_connection
[2025-03-01T17:28:53.318+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:28:53.318+0000] {override.py:1912} INFO - Created Permission View: can read on DAG Run:test_postgres_connection
[2025-03-01T17:28:53.322+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:28:53.320+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T17:28:53.350+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:28:53.350+0000] {dag.py:3262} INFO - Creating ORM DAG for test_postgres_connection
[2025-03-01T17:28:53.357+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:28:53.355+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T17:28:53.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 1.289 seconds
[2025-03-01T17:29:23.614+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:29:23.615+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:29:23.617+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:29:23.617+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:29:23.659+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:29:23.658+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T17:29:23.662+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:29:23.686+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:29:23.686+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T17:29:23.703+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:29:23.703+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T17:29:23.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.117 seconds
[2025-03-01T17:29:53.918+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:29:53.919+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:29:53.923+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:29:53.922+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:29:53.944+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:29:53.944+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T17:29:53.955+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:29:53.973+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:29:53.973+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T17:29:53.991+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:29:53.990+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T17:29:54.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.096 seconds
[2025-03-01T17:30:24.170+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:30:24.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:30:24.178+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:30:24.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:30:24.202+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:30:24.201+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T17:30:24.205+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:30:24.228+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:30:24.228+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T17:30:24.280+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:30:24.280+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T17:30:24.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.176 seconds
[2025-03-01T17:30:54.512+0000] {processor.py:186} INFO - Started process (PID=94) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:30:54.517+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:30:54.527+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:30:54.527+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:30:54.560+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:30:54.560+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T17:30:54.564+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:30:54.582+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:30:54.582+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T17:30:54.622+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:30:54.621+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T17:30:54.688+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.184 seconds
[2025-03-01T17:31:24.842+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:31:24.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/db_connection_test_dag.py for tasks to queue
[2025-03-01T17:31:24.845+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:31:24.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:31:24.866+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:31:24.866+0000] {base.py:84} INFO - Retrieving connection 'postgres_weather_conn'
[2025-03-01T17:31:24.870+0000] {processor.py:925} INFO - DAG(s) 'test_postgres_connection' retrieved from /opt/airflow/dags/db_connection_test_dag.py
[2025-03-01T17:31:24.889+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:31:24.889+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-03-01T17:31:24.906+0000] {logging_mixin.py:190} INFO - [2025-03-01T17:31:24.905+0000] {dag.py:4180} INFO - Setting next_dagrun for test_postgres_connection to None, run_after=None
[2025-03-01T17:31:24.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/db_connection_test_dag.py took 0.087 seconds
